version: '3.8'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./conf/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
#    build:
#      context: ./docker/proxy
    ports:
      - "443:443"
    networks:
      app_net:
        ipv4_address: 173.17.2.1
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "10443:443"
      # デバッグ用で開放
      - "8081:8080"
    volumes:
      - ./conf/app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./exportKey:/exportKey
      - ./app:/app
    depends_on:
      - proxy
    networks:
      app_net:
        ipv4_address: 173.17.2.2

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

